# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 472174bffc4a8b2379c82119de7b2aa0ce04224d34bb914061767d195954b1184744e8c6397b0f0d158bd8ec87b9005604c831b0396a3b678fe55be3fbb4e7d2

test:
  secret_key_base: b1b5b11ab1f71eff50d7acfeb42be4c8c6ed83d799281eebc157e93e8a09193c4242e40aef7adaee725f931af81b7c5b8e4b90d0b3ae5e04b2cbc1608e453197

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
